### ISSUE TITLE
restore.sh (cannot find the path specified)

### ISSUE THREAD

**Issue by En-J-A** [HLTCHKUST/BiToD#2]
thank you for this work but I could not execute this line

`cd ./db && bash restore.sh` in my windows 10 and pycharm environment

 and the error is

```
'bash' is not recognized as an internal or external command,
operable program or batch file.
```
 then I tried to run
`cd ./db && restore.sh` 
it is moved my to the sh file and when run it I got

```
(base) C:\Users\~\BiToD-main\BiToD-main\db>/bin/sh "C:/Users/~/BiToD-main/BiToD-main/db/restore.sh"
The system cannot find the path specified.
```
it took me out of the (env) to (base)

I tried to add  t my path in the system variable

is there a way to run it in windows, please?

**Comment by En-J-A** [comment]
What is the purpose of this command?
`mongorestore --dir=db
`

**Comment by zlinao** [comment]
Hi, you shold first install mongoDB in your Windows, then run `mongorestore --dir=db` in the **BiToD/db** folder to setup the service API server.

**Comment by En-J-A** [comment]
OK it works now thank you. **Now I want to add a new json file , I created as a collection in mongoDB, but how can I save it as .bson and .json.metadata files like yours.**

**Comment by En-J-A** [comment]
OK. thank you very much
