### ISSUE TITLE
EOFError: No valid references for a sentence!

### ISSUE THREAD

**Issue by En-J-A** [HLTCHKUST/BiToD#3]
hello, after getting the training result, I got an error during the evaluation step of the training of t5 en or t5 zh

```
*** Evaluate ***
***** Running Evaluation *****
  Num examples = 6598
  Batch size = 8
100% 825/825 [16:48<00:00,  1.17s/it]Traceback (most recent call last):
  File "~/BiToD-main/train.py", line 608, in <module>
    main()
  File "/BiToD-main/train.py", line 565, in main
    max_length=data_args.val_max_target_length, num_beams=data_args.num_beams, metric_key_prefix="eval"
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer_seq2seq.py", line 75, in evaluate
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 1783, in evaluate
    metric_key_prefix=metric_key_prefix,
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 1959, in prediction_loop
    metrics = self.compute_metrics(EvalPrediction(predictions=preds, label_ids=label_ids))
  File "~/BiToD-main/train.py", line 518, in compute_metrics
    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
  File "/usr/local/lib/python3.7/dist-packages/datasets/metric.py", line 403, in compute
    output = self._compute(predictions=predictions, references=references, **kwargs)
  File "/root/.cache/huggingface/modules/datasets_modules/metrics/sacrebleu/4dba4e29caa3766d885f0b9cde070fedb22ac3190c264a6454b8ea6703ddd466/sacrebleu.py", line 128, in _compute
    use_effective_order=use_effective_order,
  File "/usr/local/lib/python3.7/dist-packages/sacrebleu/compat.py", line 36, in corpus_bleu
    sys_stream, ref_streams, use_effective_order=use_effective_order)
  File "/usr/local/lib/python3.7/dist-packages/sacrebleu/metrics/bleu.py", line 286, in corpus_score
    raise EOFError("No valid references for a sentence!")
EOFError: No valid references for a sentence!
100% 825/825 [16:49<00:00,  1.22s/it]
```
I installed the libraries in requirements file and run the code in colab with GPU

what can I do?

**Comment by zlinao** [comment]
Hi, have you saved the model checkpionts? If yes, you can directly evaluate the trained model with the evaluation script.

**Comment by En-J-A** [comment]
OK. I will try with it .

**Comment by En-J-A** [comment]
> Hi, have you saved the model checkpionts? If yes, you can directly evaluate the trained model with the evaluation script.


you mean like this:
`python evaluate.py --model_path save/en_mt5-5e-4 --setting en --reference_file_path data/en_valid.json --save_prefix t5_`

In this case do I need to change the line
`        path_test = ["data/en_test.json"]
`to
`        path_test = ["data/en_valid.json"]
`to work on valid file only?

**Comment by En-J-A** [comment]
If I use this statement 
`python train.py --model_name_or_path save/en_mt5_5e_4/ --do_eval --train_file data/preprocessed/en_train.json --validation_file data/preprocessed/en_valid.json --learning_rate 5e-4  --num_train_epochs 8 --source_lang en_XX --target_lang en_XX  --logging_steps 100 --save_steps 2000 --output_dir save/en_mt5_5e_4 --per_device_train_batch_size=8 --per_device_eval_batch_size=8 --gradient_accumulation_steps 8 --overwrite_output_dir --predict_with_generate`

I got the same error
```
    raise EOFError("No valid references for a sentence!")
EOFError: No valid references for a sentence!
```
@zlinao please, which script is useful for the evaluation?

**Comment by zlinao** [comment]
> > Hi, have you saved the model checkpionts? If yes, you can directly evaluate the trained model with the evaluation script.
> 
> you mean like this:
> `python evaluate.py --model_path save/en_mt5-5e-4 --setting en --reference_file_path data/en_valid.json --save_prefix t5_`
> 
> In this case do I need to change the line
> ` path_test = ["data/en_test.json"]`to
> ` path_test = ["data/en_valid.json"]`to work on valid file only?

Yes, you need to set the --reference_file_path data/en_valid.json to evaluate the trained model on English validation set, and change the line https://github.com/HLTCHKUST/BiToD/blob/a9bd74de9eecdc3d875cb4ebf6a6beaf9c30c2ff/preprocess.py#L333 to data_test = read_data(args, path_dev, tokenizer, max_history)

**Comment by En-J-A** [comment]
> > > Hi, have you saved the model checkpionts? If yes, you can directly evaluate the trained model with the evaluation script.
> > 
> > 
> > you mean like this:
> > `python evaluate.py --model_path save/en_mt5-5e-4 --setting en --reference_file_path data/en_valid.json --save_prefix t5_`
> > In this case do I need to change the line
> > ` path_test = ["data/en_test.json"]`to
> > ` path_test = ["data/en_valid.json"]`to work on valid file only?
> 
> Yes, you need to set the --reference_file_path data/en_valid.json to evaluate the trained model on English validation set, and change the line
> 
> https://github.com/HLTCHKUST/BiToD/blob/a9bd74de9eecdc3d875cb4ebf6a6beaf9c30c2ff/preprocess.py#L333
> 
> to data_test = read_data(args, path_dev, tokenizer, max_history)

Ok, I tried to evaluate with this script and I got a result by using --reference_file_path data/en_valid.json

but I want to understand how can I get the eval_results.json file while this command gives me the above error

`python train.py --model_name_or_path google/mt5-small --do_train --do_eval --train_file data/preprocessed/en_train.json --validation_file data/preprocessed/en_valid.json ………
`
In this case, what is the difference between valid and test files? 

While training the model( train.py ), Is there a need to use  data/preprocessed/en_valid.json in training?

I'll appreciate any advice @zlinao .
Thank you again for your time.

**Comment by En-J-A** [comment]
I wonder how can I choose the best checkpoints if I use the evaluation script without using --do_eval in the training script??
