### ISSUE TITLE
how to identify domain information for each dialogue

### ISSUE THREAD

**Issue by Charles-ux-bit** [HLTCHKUST/BiToD#6]
Thanks for your valuable work, and I I would like to know how to identify domain information for each dialogue from the json file. Thanks!

**Comment by zlinao** [comment]
Hi, you can find the domain in the active intent. It follows the pattern like <domain>_en_US_XX. E.g., if the active intent is restaurants_en_US_search, then the domain is restaurant.

**Comment by Charles-ux-bit** [comment]
thx, but the active intent is in all the conversational turns, and there are multiple domains for most conversations.
I believe that each conversation should have its main topic, so its corresponding domains should be as few as possible, right?
